production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true
development:
  sessions:
    default:
      uri: mongodb://localhost:27017/books
      options:
        skip_version_check: true
        safe: true
